-- ============================================
-- INSERTAR CATEGORÍAS
-- ============================================

INSERT INTO categorias (id, nombre) VALUES 
  ('2024-01-01T00:00:00+00:00', 'HTML/CSS'),
  ('2024-01-02T00:00:00+00:00', 'TypeScript'),
  ('2024-01-03T00:00:00+00:00', 'JavaScript'),
  ('2024-01-04T00:00:00+00:00', 'React'),
  ('2024-01-05T00:00:00+00:00', 'Angular')
ON CONFLICT DO NOTHING;

-- ============================================
-- INSERTAR COMPONENTES
-- ============================================

INSERT INTO componentes (id, nombre, descripcion, codigo_ejemplo, categoria_id) VALUES 
  ('2024-01-10T10:00:00+00:00', 'Floating Lines', 'Animación de líneas flotantes con Three.js y GLSL shaders', 'import * as THREE from "three";\n\nconst scene = new THREE.Scene();\nconst camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);\nconst renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });\n\nrenderer.setSize(window.innerWidth, window.innerHeight);\ndocument.body.appendChild(renderer.domElement);\n\nconst geometry = new THREE.BufferGeometry();\nconst vertices = [];\n\nfor (let i = 0; i < 1000; i++) {\n  vertices.push(Math.random() * 2000 - 1000);\n  vertices.push(Math.random() * 2000 - 1000);\n  vertices.push(Math.random() * 2000 - 1000);\n}\n\ngeometry.setAttribute("position", new THREE.BufferAttribute(new Float32Array(vertices), 3));\n\nconst material = new THREE.PointsMaterial({ color: 0x5227ff, size: 2 });\nconst points = new THREE.Points(geometry, material);\nscene.add(points);\n\ncamera.position.z = 500;\n\nfunction animate() {\n  requestAnimationFrame(animate);\n  points.rotation.x += 0.0001;\n  points.rotation.y += 0.0001;\n  renderer.render(scene, camera);\n}\n\nanimate();', '2024-01-01T00:00:00+00:00'),

  ('2024-01-11T10:00:00+00:00', 'Gradient Button', 'Botón con gradiente animado y efecto hover', '<button class="gradient-btn">\n  <span class="btn-text">Click me</span>\n  <span class="btn-shine"></span>\n</button>\n\n<style>\n.gradient-btn {\n  position: relative;\n  padding: 12px 32px;\n  background: linear-gradient(135deg, #5227ff 0%, #7047ff 100%);\n  border: 1px solid rgba(82, 39, 255, 0.5);\n  border-radius: 8px;\n  color: white;\n  font-weight: 600;\n  cursor: pointer;\n  overflow: hidden;\n  transition: all 0.3s ease;\n}\n\n.gradient-btn:hover {\n  transform: translateY(-2px);\n  box-shadow: 0 8px 24px rgba(82, 39, 255, 0.4);\n}\n\n.btn-shine {\n  position: absolute;\n  top: 0;\n  left: -100%;\n  width: 100%;\n  height: 100%;\n  background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\n  transition: left 0.5s ease;\n}\n\n.gradient-btn:hover .btn-shine {\n  left: 100%;\n}\n</style>', '2024-01-01T00:00:00+00:00'),

  ('2024-01-12T10:00:00+00:00', 'Card Component', 'Tarjeta con sombra y efecto hover', '<div class="card">\n  <div class="card-header">\n    <h3>Título de la Tarjeta</h3>\n  </div>\n  <div class="card-body">\n    <p>Contenido de la tarjeta con descripción y detalles.</p>\n  </div>\n  <div class="card-footer">\n    <button class="card-btn">Leer más</button>\n  </div>\n</div>\n\n<style>\n.card {\n  background: var(--dark-800);\n  border: 1px solid var(--dark-700);\n  border-radius: 12px;\n  overflow: hidden;\n  transition: all 0.3s ease;\n  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\n}\n\n.card:hover {\n  transform: translateY(-8px);\n  box-shadow: 0 12px 32px rgba(82, 39, 255, 0.2);\n  border-color: var(--primary-500);\n}\n\n.card-header {\n  padding: 20px;\n  border-bottom: 1px solid var(--dark-700);\n}\n\n.card-body {\n  padding: 20px;\n}\n\n.card-footer {\n  padding: 20px;\n  border-top: 1px solid var(--dark-700);\n  display: flex;\n  justify-content: flex-end;\n}\n\n.card-btn {\n  padding: 8px 16px;\n  background: var(--primary-500);\n  color: white;\n  border: none;\n  border-radius: 6px;\n  cursor: pointer;\n}\n</style>', '2024-01-01T00:00:00+00:00'),

  ('2024-01-20T10:00:00+00:00', 'API Service', 'Servicio Angular para consumir APIs REST', 'import { Injectable } from "@angular/core";\nimport { HttpClient } from "@angular/common/http";\nimport { Observable } from "rxjs";\n\n@Injectable({\n  providedIn: "root"\n})\nexport class ApiService {\n  private apiUrl = "https://api.example.com";\n\n  constructor(private http: HttpClient) {}\n\n  getData(): Observable<any> {\n    return this.http.get(`${this.apiUrl}/data`);\n  }\n\n  postData(data: any): Observable<any> {\n    return this.http.post(`${this.apiUrl}/data`, data);\n  }\n\n  updateData(id: string, data: any): Observable<any> {\n    return this.http.put(`${this.apiUrl}/data/${id}`, data);\n  }\n\n  deleteData(id: string): Observable<any> {\n    return this.http.delete(`${this.apiUrl}/data/${id}`);\n  }\n}', '2024-01-02T00:00:00+00:00'),

  ('2024-01-21T10:00:00+00:00', 'State Management', 'Gestor de estado con Angular Signals', 'import { Injectable, signal, computed } from "@angular/core";\n\ninterface AppState {\n  count: number;\n  user: { name: string; email: string } | null;\n  loading: boolean;\n}\n\n@Injectable({\n  providedIn: "root"\n})\nexport class StateService {\n  private state = signal<AppState>({\n    count: 0,\n    user: null,\n    loading: false\n  });\n\n  count = computed(() => this.state().count);\n  user = computed(() => this.state().user);\n  loading = computed(() => this.state().loading);\n\n  increment() {\n    this.state.update(s => ({ ...s, count: s.count + 1 }));\n  }\n\n  decrement() {\n    this.state.update(s => ({ ...s, count: s.count - 1 }));\n  }\n\n  setUser(user: any) {\n    this.state.update(s => ({ ...s, user }));\n  }\n\n  setLoading(loading: boolean) {\n    this.state.update(s => ({ ...s, loading }));\n  }\n}', '2024-01-02T00:00:00+00:00'),

  ('2024-01-30T10:00:00+00:00', 'Debounce Function', 'Función para debounce de eventos', 'function debounce(func, wait) {\n  let timeout;\n  return function executedFunction(...args) {\n    const later = () => {\n      clearTimeout(timeout);\n      func(...args);\n    };\n    clearTimeout(timeout);\n    timeout = setTimeout(later, wait);\n  };\n}\n\nconst handleSearch = debounce((query) => {\n  console.log("Buscando:", query);\n}, 300);\n\ninput.addEventListener("input", (e) => {\n  handleSearch(e.target.value);\n});', '2024-01-03T00:00:00+00:00'),

  ('2024-01-31T10:00:00+00:00', 'Local Storage Manager', 'Gestor de localStorage con validación', 'class StorageManager {\n  static set(key, value) {\n    try {\n      localStorage.setItem(key, JSON.stringify(value));\n      return true;\n    } catch (error) {\n      console.error("Error saving to localStorage:", error);\n      return false;\n    }\n  }\n\n  static get(key) {\n    try {\n      const item = localStorage.getItem(key);\n      return item ? JSON.parse(item) : null;\n    } catch (error) {\n      console.error("Error reading from localStorage:", error);\n      return null;\n    }\n  }\n\n  static remove(key) {\n    try {\n      localStorage.removeItem(key);\n      return true;\n    } catch (error) {\n      console.error("Error removing from localStorage:", error);\n      return false;\n    }\n  }\n\n  static clear() {\n    try {\n      localStorage.clear();\n      return true;\n    } catch (error) {\n      console.error("Error clearing localStorage:", error);\n      return false;\n    }\n  }\n}', '2024-01-03T00:00:00+00:00')
ON CONFLICT DO NOTHING;
