

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.pusykqxuxkbfvnryarww&password=*Torrecilla180
spring.datasource.driverClassName=org.postgresql.Driver

# 2. Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Puerto dinámico (Obligatorio para que Railway no falle al desplegar)
server.port=${PORT:8080}
