# Configuración para modo CLI (Command Line Interface)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.pusykqxuxkbfvnryarww&password=*Torrecilla180
spring.datasource.driverClassName=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Shell
spring.shell.interactive.enabled=true
spring.shell.command.scan.enabled=true
